<div id="user_list" class="box">
    <div class="box-header with-border">
        <h3 class="box-title">全局<?=$type_name?>列表</h3>
        <a href="<?=$c->url('new')?>" type="button" class="btn btn-success btn-sm" style="margin-left:20px;">添加扩展<?=$type_name?></a>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table class="table table-bordered table-striped">
            <tbody><tr>
                <th>权限名称</th>
                <th>变量名</th>
                <th>默认值</th>
                <th>值类型</th>
                <th>备选值</th>
                <th>备选值类型</th>
                <th style="width: 150px" class="text-center">操作</th>
            </tr>
            <?php foreach($global as $row){ ?>
            <tr>
                <td><?=$row['name']?></td>
                <td><?=$row['extend_name']?></td>
                <td><?=$row['extend_value']?></td>
                <td><?=$row['extend_value_type']?></td>
                <td><?=$row['extend_items']?></td>
                <td><?=$row['extend_items_type']?></td>
                <td class="text-center">
                    <a href="<?=$c->url('update',['item_id'=>$row['extend_id']])?>">修改</a>
                    <a class="del" href="<?=$c->url('delete',['item_id'=>$row['extend_id']])?>">删除</a>
                </td>
            </tr>
            <?php } ?>
            </tbody></table>
    </div>
    <!-- /.box-body -->
    <div class="box-footer clearfix"><ul class="pagination pagination-sm no-margin pull-right"></ul></div>
</div>

<div id="user_list" class="box">
    <div class="box-header with-border">
        <h3 class="box-title">依附于权限菜单的<?=$type_name?>列表</h3>
        <a href="<?=$c->url('new')?>" type="button" class="btn btn-success btn-sm" style="margin-left:20px;">添加扩展<?=$type_name?></a>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table class="table table-bordered table-striped">
            <tbody><tr>
                <th>权限菜单</th>
                <th><?=$type_name?>名称</th>
                <th>变量名</th>
                <th>默认值</th>
                <th>值类型</th>
                <th>备选值</th>
                <th>备选值类型</th>
                <th style="width: 150px" class="text-center">操作</th>
            </tr>
            <?php foreach($menus as $row) { ?>
            <tr>
                <td valign="middle" style="vertical-align:middle;"><?=$row['rule_names']?></td>
                <td><?=$row['name']?></td>
                <td><?=$row['extend_name']?></td>
                <td><?=$row['extend_value']?></td>
                <td><?=$row['extend_value_type']?></td>
                <td><?=$row['extend_items']?></td>
                <td><?=$row['extend_items_type']?></td>
                <td class="text-center">
                    <a href="<?=$c->url('update',['item_id'=>$row['extend_id']])?>">修改</a>
                    <a class="del" href="<?=$c->url('delete',['item_id'=>$row['extend_id']])?>">删除</a>
                </td>
            </tr>
            <?php } ?>
            
            </tbody></table>
    </div>
    <!-- /.box-body -->
    <div class="box-footer clearfix"><ul class="pagination pagination-sm no-margin pull-right"></ul></div>
</div>
<script>
    $(function(){
        $('.del').click(function(e){
            var obj = $(e.target);
            showDialogs({
                title:'是否删除此功能菜单',
                // body:'如果删除的菜单下面有子菜单，那么会将子菜单的父级设置成【根节点】',
                ok:{text:'确认',click:function(o){
                        $.ajax(obj.attr('href'),{
                            method:'delete'
                        }).done(function(d){
                            location.reload();
                        })
                    }},
                close:{text:'取消',click:function(o){o.close()}}
            });
            return false;
        })
    });
</script>

