<style>
    h4.box-title{
        background: #d2d6de;
        padding: 10px;
        color: #222d32;
    }
    /* h4.select{
        background: white;
        border-style: solid;
        border-width: 2px;
        border-color: #d2d6de;
        border-bottom:none;
        border-radius: 10px;
        border-bottom-left-radius: 0;
        border-bottom-right-radius: 0;
    } */
    /* h4.unselect{
        background: #d2d6de;
    } */
    .role_items{

    }
    /* box */
    .box.role-box{
        border-top:none;
    }

    /* header */
    .box.role-box .box-header{
        border-bottom:2px solid #3c8dbc;
        margin-top:0;
        height:auto;
        padding:20px 20px 0;
    }

    .role-title{
        display:inline-block;
        position:relative;
        z-index:10;
        margin:0 5px 0 0;
        bottom:0;
    }

    .role-title .box-title{
        color:#333;
        border-radius:10px 10px 0 0;
        background-color:#f1f1f1;
        padding:6px 10px;;
        line-height:normal;
        font-weight:normal;
        position:relative;
        z-index:20;
        margin-bottom:0;
    }
    .role-title .box-title.role-title-input{
        /*padding-bottom:7px;*/
    }

    .role-title.select .box-title,.role-title:hover .box-title{
        background-color:#3c8dbc;
        color:#fff;
    }

    /* fa-remove */
    .role-title .remove{
        position:absolute;right:-5px;top:-5px;
        background-color:#e2e2e2;
        color:#ccc;
        display:inline-block;
        width:22px;height:22px;
        border-radius:50%;
        text-align:center;
        line-height:21px;
        font-size:14px;
        z-index:25;
    }
    .role-title .remove:hover,.role-title.select .remove:hover{
        color:#dd4444;
        background-color:#ffeeee;
    }
    .role-title.select .remove{
        background-color:#def2fd;
        color:#3c8dbc;
    }


    .role-title input[type='radio']{
        width:0;
        opacity:0;
        display: none;
    }


    .box.role-box .box-header .role-title-input input[name='role_name']{
        height: 28px;
        font-size: 14px;
        padding: 0 5px;
        background-color:#fff;
        border:1px solid #ddd;
    }

    .box.role-box .box-header .role-title-input.select input[name='role_name']{
        border:1px solid #3c8dbc;
    }

    /* 表格 */
    .role-menu{
        margin-top:20px;
    }
    .role-menu .table-bordered>tbody>tr>th{
        background-color:#daebf5;
        color:#2278ab;
        font-size:16px;
        font-weight:700;
    }
    .role-menu .table-bordered>tbody>tr>th i{
        margin-right:5px;
        display:inline-block;
    }
    .role-small-title.title0 label{
        font-weight:bold;
    }

    .role-menu .table-bordered{
        border:none;
    }

    .role-label{
        font-size:16px;
        font-weight:normal;
        color:#333;
    }
    .role-label input{opacity:0;width:0;}
    .role-label input:checked+i{
        color:#4db55a;
    }
    .role-label i{
        color:#ccc;
    }

    .role-save-btn{
        margin:30px auto;
        width:140px;
        display:block;
        height:45px;
        font-size:20px;
        letter-spacing:2px;
    }
    .min-th{
        padding:0 !important;
        font-size:14px !important;
        text-align: center !important;
    }
    .ext{
        width: 100%;
        border-style: solid;
        border-width: 1px;
        border-color: #00acd6;
        border-radius: 5px;
        height: 100%;
        overflow: hidden;
    }
    .ext .form-group {
        margin: 5px;
        height: 100%;
        overflow: hidden;
        display: flex;
        align-items: center;
    }
    .ext label{
        margin-bottom: 0;
    }
    .valign{
        vertical-align: middle !important;
    }
</style>
<form id="role_form" method="post" action="<?=$c->url('update', ['item_id'=>$role_id])?>">
<div id="user_list" class="box role-box">
    <!-- <div class="box-header with-border" style="margin-top: -35px;height: 45px;display: inline-block;"> -->
    <div class="box-header with-border">
        <?php foreach($roles as $i => $role){ ?>
        <!-- <h4 class="role-title box-title<?=$role_id==$role->role_id?' select':' unselect'?>"> -->
        <h4 class="role-title <?=$role_id==$role->role_id?' select':' unselect'?>">
            <label class="box-title" style="font-size:16px;"><input value="<?=$role->role_id?>" class="role_items" name="role_id" type="radio"<?=$role_id==$role->role_id?' checked':''?>><?=$role->name?></label>
            <?php if($i>0){ ?>
                <i class="remove operate-btn fa fa-remove" data-type="delete" data-url="<?=$c->url('delete',['item_id'=>$role->role_id])?>"></i>
            <?php } ?>
        </h4>
        <?php } ?>
        <!-- <h4 id="new_role" class="unselect" style="height: 44px;position: relative;display: inline-block;padding: 8px;"> -->
        <h4 id="new_role" class="role-title<?=$c->getItemId()?' unselect':' select'?>" style="margin-bottom: 4px;position: absolute;">
            <?php if($is_new){ ?>
                <label class="unselect box-title role-title-input" style="margin-bottom: -5px;padding: 0;">
                    <input value="new" class="role_items" name="role_id" type="radio">
                    <input style="border-radius:5px;margin: 5px;color:black;" name="role_name" type="text" autofocus value="" placeholder="请输入新角色名称">
                </label>
            <?php }else{ ?>
                <a href="<?=$c->url('append')?>" class="btn btn-info btn-sm">添加新角色</a>
            <?php } ?>
        </h4>
    </div>
    
    <!-- /.box-header -->
    <div class="box-body role-menu">
        <table class="table table-bordered table-striped">
            <tr>
                <th rowspan="2"><i class="fa fa-bars"></i>菜单项</th>
                <th colspan="4" class="min-th" style="font-size:16px !important;">全局权限</th>
                <th colspan="4" class="min-th" style="font-size:16px !important;">个人权限</th>
            </tr>
            <tr>
                <th class="min-th" width="35">增</th>
                <th class="min-th" width="35">删</th>
                <th class="min-th" width="35">改</th>
                <th class="min-th" width="35">查</th>
                <th class="min-th" width="35">增</th>
                <th class="min-th" width="35">删</th>
                <th class="min-th" width="35">改</th>
                <th class="min-th" width="35">查</th>
            </tr>
            <?php foreach($menus as $row=>$menu){
                $class = 'valign title'.$menu['level'];
                if(!in_array($menu['menu_id'], $menus)) $class .= ' role-small-title';
            ?>
            <tr>
                <td class="<?=$class?>"<?=$menu['router']?'':' colspan="9"'?> style="padding-left:<?=$menu['level'] * 30 + 10?>px;">
                    <?=$menu['name']?>
                    <?php if(isset($configs[$menu['menu_id']])){ ?>
                    <span class="text-info" style="cursor:pointer;margin-left:10px;" onclick="toggleExt(event, <?=$row?>)">【扩展权限<i class="fa fa-plus"></i>】</span>
                    <?php } ?>
                </td>
                <?php if($menu['router']){ for($i=7; $i>=0; $i--){ ?>
                <?php $checked = ((1<<$i) & ($menus[$menu['menu_id']]??0)) === (1<<$i) ? ' checked' : ''; ?>
                <td class="<?=$class?>">
                    <label class="role-label" style="height: 18px;"><input value="1" name="menu_id[<?=$menu['menu_id']?>][<?=$i?>]" type="checkbox"<?=$checked?>><i class="fa fa-check-square"></i></label>
                </td>
                <?php }} ?>
            </tr>
            <?php if(isset($configs[$menu['menu_id']])){ ?>
            <tr id="extend_<?=$row?>" style="display: none;">
                <td colspan="9" style="padding-left:<?=$menu['level'] * 30 + 10?>px;">
                    <div style="border-style: dashed;border-color: #0b97c4;border-width:1px;padding: 10px;">
                        <?=$configs[$menu['menu_id']]?>
                    </div>
                </td>
            </tr>
            <?php }} ?>
        </table>
    </div>
    <!-- /.box-body -->
</div>

<?php if(isset($configs[0])) { ?>
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">全局扩展权限</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus text-info"></i></button>
        </div>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <div class="box-body">
        <?=$configs[0]?>
    </div>
</div>
<?php } ?>

    <button type="submit" class="btn role-save-btn btn-primary">保存</button>
</form>
<script>
    function toggleExt(e, row){
        var o = $(e.currentTarget);
        var i = o.find('i');
        if(i.hasClass('fa-plus')){ //  fa-minus:- fa-plus
            $('#extend_'+row).show();
            i.removeClass('fa-plus').addClass('fa-minus');
        }else{
            $('#extend_'+row).hide();
            i.removeClass('fa-minus').addClass('fa-plus');
        }
    }
$(function(){
    var url = $('#role_form').attr('action');
    $('.box-title .role_items').change(function(e){
        var item_id = $(e.target).val();
        url = url.replace(new RegExp('/item/\\d+'), '/item/'+item_id);
        location.href = url;
    });
    $('.remove').click(function(e){
        var url = $(e.target).data('url');

        showDialogs({
            title:'是否删除此角色',
            body:'删除后，此角色下面的用户将无法登录，需要单独为这些用户再分配角色',
            ok:{
                text:'确认',
                click:function(t){
                    $.ajax(url,{method:'delete'}).done(function(d){
                        window.location.href = '<?=$c->url()?>';
                    });
                }
            },
            close:{
                text:'取消',
                click:function(t){t.close()}
            }
        });
    })
});
</script>