version: "3"
services:
  php:
    env_file:
      - ./config.env
    build:
      context: ../
      dockerfile: ./docker/build-phalcon-dockerfile
      #dockerfile: ./docker/test-dockerfile
      args: 
        WITH_MYSQL: ${WITH_MYSQL:-yes}
        WITH_REDIS: ${WITH_REDIS:-yes}
        WITH_ALI_SOURCE: ${WITH_ALI_SOURCE:-no}
        WITH_PA_PASSWORD: ${WITH_PA_PASSWORD:-no}
        PA_PASSWORD: ${PA_PASSWORD:-no}
        WITH_COMPOSER: ${WITH_COMPOSER:-no}
    volumes:
      - ../src/:/var/www/html
      - ./sites-enabled:/etc/apache2/sites-enabled
    ports:
      - ${PORT}:80
    restart: always
