version: "3"
services:
  pa:
    container_name: pa
    image: registry.cn-hangzhou.aliyuncs.com/vanni/phalcon:7.4-apache
    volumes:
      - ../:/var/www/pa
    restart: always
    ports:
      - 88:80