<style>
.box-body label{
    text-align: right;
    line-height: 35px;
}
.must-start::after{
    content: '*';
    color: red;
    font-size: 20px;
    position: absolute;
    top: 2px;
    padding-left: 5px;
}
</style>
<form onsubmit="return checkForm();" method="post" action="<?=$c->getItemId() ? $c->url('update',['item_id'=>$c->getItemId()]) : $c->url('new') ?>">
<div class="box box-primary">
    <div class="box-body">
        <div class="row">
            <!-- 中文名称 -->
            <div class="col-sm-6">
                <div class="form-group">
                    <label for="name" class="col-sm-4 control-label must-start">中文名称</label>
                    <div class="col-sm-8">
                        <input name="name" type="text" class="form-control" id="name" value="<?=$data['name']??''?>" placeholder="输入名字">
                    </div>
                </div>
            </div>
    
            <!-- 变量名称 -->
            <div class="col-sm-6">
                <div class="form-group">
                    <label for="extend_name" class="col-sm-4 control-label must-start">变量名称</label>
                    <div class="col-sm-8">
                        <?php if($c->getParam('type')=='rule') { ?>
                        <div class="input-group">
                        <span class="input-group-addon">
                            <label style="line-height: normal;margin: 0;"><input name="is_action_name" value="1" <?=empty($data['is_action_name'])?'':' checked'?> style="top: 2px;position: relative;" type="checkbox">与动作函数同名</label>
                        </span>
                        <?php } ?>
                            <input name="extend_name" type="text" class="form-control" id="extend_name" value="<?=$data['extend_name']??''?>" placeholder="输入名字">
                        <?php if($c->getParam('type')=='rule') { ?>
                        </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
            
            <!-- 依附位置 -->
            <div class="col-sm-6">
                <label class="col-sm-4 must-start" for="rule_id"><?=$type_name?>范围</label>
                <div class="col-sm-8">
                    <select id="rule_id" name="rule_id" class="form-control">
                        <?php $rule_id = $data['rule_id'] ?? ''; ?>
                        <option<?=$rule_id==0?' selected':''?>>全局<?=$type_name?></option>
                        <optgroup label="权限菜单">
                        <?php foreach($menus as $m){ ?>
                        <option<?=$rule_id==$m['rule_id']?' selected':''?> value="<?=$m['rule_id']?>"><?=str_repeat('　　',$m['level']).$m['name']?></option>
                        <?php } ?>
                        </optgroup>
                    </select>
                </div>
            </div>
    
            <!-- 说明 -->
            <div class="col-sm-6">
                <label class="col-sm-4" for="description"><?=$type_name?>说明</label>
                <div class="col-sm-8">
                    <input name="description" type="text" class="form-control" id="description" value="<?=$data['description']??''?>" placeholder="输入名字">
                </div>
            </div>
            
            <!-- 值类型 -->
            <div class="col-sm-6">
                <label class="col-sm-4 must-start" for="extend_value_type">值类型</label>
                <div class="col-sm-8">
                    <select id="extend_value_type" name="extend_value_type" class="form-control">
                        <option value="text"<?=($data['extend_value_type']??'')=='text' ? ' selected':''?>>text</option>
                        <option value="list"<?=($data['extend_value_type']??'')=='list' ? ' selected':''?>>list</option>
                        <option value="hash"<?=($data['extend_value_type']??'')=='hash' ? ' selected':''?>>hash</option>
                    </select>
                </div>
            </div>
            
            <!-- 备选项类型 -->
            <div class="col-sm-6">
                <label class="col-sm-4 must-start" for="extend_items_type">选项类型</label>
                <div class="col-sm-8">
                    <select id="extend_items_type" name="extend_items_type" class="form-control">
                        <option value="null"<?=($data['extend_items_type']??'')=='null' ? ' selected':''?>>null</option>
                        <option value="callback"<?=($data['extend_items_type']??'')=='callback' ? ' selected':''?>>callback</option>
                        <option value="hash"<?=($data['extend_items_type']??'')=='hash' ? ' selected':''?>>hash</option>
                    </select>
                </div>
            </div>
    
            <!-- 默认值 -->
            <div class="col-sm-6">
                <label class="col-sm-4 must-start" for="extend_value">默认值</label>
                <div class="col-sm-8">
                    <textarea name="extend_value" id="extend_value" class="form-control"><?=$data['extend_value']??''?></textarea>
                </div>
            </div>

            <!-- 备选值 -->
            <div class="col-sm-6">
                <label class="col-sm-4" for="extend_items">选项值</label>
                <div class="col-sm-8">
                    <textarea name="extend_items" id="extend_items"  class="form-control"><?=$data['extend_items']??''?></textarea>
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer">
        <button type="button" class="btn btn-default" onclick="history.back()">取消</button>
        <button type="submit" class="btn btn-info pull-right">提交</button>
    </div>
</div>
</form>
<script>
    function checkForm(){
        if($('#name').val()==''){
            showDialogs({
                body:'请输入名称',
                delay:1500
            });
            return false;
        }
        if($('#extend_name').val()==''){
            showDialogs({
                body:'请输入变量名称',
                delay:1500
            });
            return false;
        }
        if($('#extend_value').val()==''){
            showDialogs({
                body:'请输入默认值',
                delay:1500
            });
            return false;
        }
    }
</script>