<?php
namespace plugins\DataSource\Models;
use PowerModelBase as PMB;

class DataSources extends PMB{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setSource(\PA::$config->path('pa_db.prefix').'datasources');
    }

    public static function getSources(array $filter=[]){
        # 配置中的数据源
        $data = [];
        foreach(\PA::$config as $key=>$value){
            if(is_object($value) && $value->has('adapter')){
                $v = $value->toArray();
                $v['source_id'] = '######';
                $v['name'] = 'system';
                $v['injection_name'] = $key;
                $v['bind_events_manager'] = 1;
                $v['_CAN_SELECT_'] = 0;
                $data[] = $v;
            }
        }

        # 数据库中的数据源
        $where = [];
        self::parseWhere(['where'=>$filter], $where);
        foreach(self::find($where) as $row) $data[] = $row->toArray();

        return $data;
    }
}
