<?php
namespace plugins\Proxy\Models;
use PowerModelBase as PMB;

class ProxyMenus extends PMB{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setSource(\PA::$config->path('pa_db.prefix').'proxy_menus');
    }
}
