<style>
    .header_select{
        width: 100%;
        display: flex !important;
    }
    .header_select div,.header_select button{
        flex-basis: 140px;
        display: inline;
        margin-right:10px;
    }
    .table_base{
        display: flex;
        flex-wrap: wrap;
    }
    .table_base .close{
        margin-right:-10px;
        margin-top:-5px;
    }
    .table_base .callout{
        cursor:pointer;
    }
    .table_base>div{
        flex-basis: 450px;
        margin:10px;
    }
    .table_row .row{
        margin-bottom: 20px;
    }
    .table_row label{
        line-height: 30px;
        margin: 0;
        padding: 0;
    }
    .my_fields td{
        padding:0 !important;
        margin:0;
        vertical-align: middle !important;
    }




</style>
<link rel="stylesheet" href="/dist/css/vue.filters.component.css">
<script src="/dist/plugins/vue/vue.js"></script>
<script src="/dist/js/vue.filters.component.js"></script>
<script>
// 所有数据源和表
let sources = <?=json_encode($sources)?>;
let all_menus = <?=json_encode($all_menus)?>;
let tables = [
    {
        fields:[
            {id:1,field:'user_id',name:'用户ID',tooltip:'这个是用户的ID',width:10,sort:0,filter:1,show:1,render:'',type:'text',params:{},icon:'',class:''},
            {id:1,field:'name',name:'用户名',tooltip:'',width:10,sort:1,filter:1,show:1,render:'',type:'timestamp',params:{},icon:'',class:''},
            {id:1,field:'sex',name:'性别',tooltip:'',width:10,sort:1,filter:1,show:0,render:'',type:'user',params:{},icon:'',class:''},
            {id:1,field:'mobile',name:'手机号',tooltip:'',width:10,sort:1,filter:1,show:1,render:'',type:'media',params:{},icon:'',class:''}
        ],
        menus:[
            {id:1,name:'用户管理',icon:'fa fa-users',title:'用户表',subtitle:'',filter:[],canMin:1,canSelect:1,canEdit:1,canAppend:1,canDelete:1,canFilter:1,canClose:1},
            {id:2,name:'插件管理',icon:'fa fa-group',selected:true,title:'插件表',subtitle:'',filter:[],canMin:1,canSelect:1,canEdit:1,canAppend:1,canDelete:1,canFilter:1,canClose:0},
            {id:3,name:'角色管理',icon:'fa fa-tools',title:'角色表',subtitle:'',filter:[],canMin:1,canSelect:1,canEdit:1,canAppend:1,canDelete:1,canFilter:1,canClose:0}
        ]
    }
];

/**
 * 显示基础参数配置
 * @param index 数字下标
 */
function showParams(data){
    let vo = new Vue({
        el:$('#base').clone().css('display','block').get(0),
        data:function(){
            return Object.assign(
                {menu_id:0},
                data,
                {menus:all_menus}
            );
        },
        methods: {
            submit:function(t){
                let sid = $('#source_id').val().split(':')[1];
                let tid = $('#table_id').val();
                let url = '<?=$add_menus_url?>'.replace('S_ID',sid).replace('T_ID',tid);
                let post = Object.assign({}, vo.$data);
                delete(post.menus);
                delete(post.fields);
                delete(post.filter);
                $.ajax(url,{method:'post',data:post}).then(d=>{
                    window['vo'].$data.menus = d;
                    t.close()
                })
            }
        }
    });
    showDialogs({
        title: "<b>添加数据表菜单</b>",
        body: vo.$el,
        close: {
            text: "取消",
            click: t => t.close()
        },
        ok: {
           text: "确定",
           click: t => vo.$data.menu_name ? vo.submit(t) : showDialogs({body:'请输入菜单名称',delay:3000,width:200},'mt')
}
    },'win-params');
}


/**
 * 显示查询条件
 * @param fields 字段
 * @param filters 默认查询条件
 * @param callback 回调函数
 */
function showFilter(fields, filters, callback){
    let vo = new Vue({
        mounted(){
            this.F = this.$refs.filters;
        },
        data:function(){
            return {
                fields:fields,
                filters:filters,
            };
        },
        el:$('<filters ref="filters" :value="filters" :fields="fields"></filters>').get(0)
    });
    showDialogs({
        title: "<b>添加数据表菜单</b>",
        body: vo.$el,
        close: {
            text: "取消",
            click: t => t.close()
        },
        ok: {
            text: "确定",
            click: t => {
                let value = vo.F.getFilters()
                let ok = vo.F.checkFilters(value)
                if(ok){
                    callback(value)
                    t.close()
                }
                else{
                    showDialogs({
                        body:'<b>请提供完整的查询条件</b>',
                        width:300,
                        delay:3000
                    },'t')
                }
            }
        }
    },'win-filter');
}


function showIcons(){

}
$(function() {
    // 当数据源变动时，数据表跟着变动
    // 当数据表变动时，数据中的基础数据 + 字段数据 + 查询参数 相应变动

    // 创建菜单列表的vue对象
    window['vo'] = new Vue({
        el:document.getElementById('vue-dom'),
        data:function () {
            return {
                current_db_index:0,
                sources:sources,
                can_add:false,
                menus:[] //tables[0].menus,
            //    fields: tables[0].fields
            };
        },
        methods:{
            setParams:function(i){
                showParams(this.menus[i]);
            },
            setFilter:function (i) {
                showFilter(Object.fromEntries(this.fields.map(v=>[v.field,v.name])), this.menus[i].filter,alert);
            },
            selectMenu:function(i){
                for(let index=0; index<this.menus.length; index++){
                    this.menus[index].selected = index == i;
                }
                Vue.set(this.menus, i, this.menus[i]);
            },
            delTable:function (i) {
                showDialogs({
                    title:'是否删除此数据表管理权限',
                    close:{
                        text:'关闭',
                        click:t=>t.close()
                    },
                    ok:{
                        text:'删除',
                        click:t=>{
                            // 提交删除
                            t.close()
                        }
                    }
                })
            },
            changeSource:function(event){
                this.current_db_index = event.currentTarget.value.split(':')[0];
            },
            addMenu:function (event) {
                showParams(
                    {menu_name:'',icon:'fa fa-users',title:'',subtitle:'',filter:[],canMin:1,canSelect:1,canEdit:1,canAppend:1,canDelete:1,canFilter:1,canClose:1,fields:[]}
                );
            },
            changeTable:function(event){
                let sid = $('#source_id').val().split(':')[1];
                let tid = $('#table_id').val();
                let url = '<?=$get_menus_url?>'.replace('S_ID',sid).replace('T_ID',tid);
                this.can_add = (sid !== '' && tid !== '');
                $.ajax(url).then(d=>{
                    console.log(d);
                    window['vo'].$data.menus = d;
                    window['vo'].$data.fields = d[0].fields;
                });
            }
        }
    });
});

</script>

<div id="vue-dom">
    <!--二级菜单-->
    <div class="box box-success">
        <div class="box-header with-border">
            <div class="box-title header_select">
                <div class="">
                    <select id="source_id" class="form-control" @change="changeSource">
                        <option value="">数据源</option>
                        <template v-for="(row, index) in sources">
                        <option :value="index + ':' + row.source_id">{{row.name}}</option>
                        </template>
                    </select>
                </div>
                <div class="">
                    <select id="table_id" class="form-control  " data-placeholder="" style="width:100%;height: auto;" @change="changeTable">
                        <option value="">数据表</option>
                        <template v-for="table in sources[current_db_index].tables">
                        <option :value="table">{{table}}</option>
                        </template>
                    </select>
                </div>
                <button type="button" class="btn btn-info btn-flat" @click="addMenu" :disabled="!can_add">添加</button>
            </div>
        </div>

        <div class="box-body table_base">
            <template v-for="(val, index) in menus">
                <div :class="val.selected ? 'callout callout-success' : 'callout bg-gray'" @click="selectMenu(index)">
                    <button type="button" class="close" @click="delTable(index)">x</button>
                    <h5>{{val.menu_name}}</h5>
                    <h4 style="display: inline;">{{val.title}}</h4>
                    <h5 style="display: inline;padding-left: 10px;">{{val.subtitle}}</h5>
                    <div style="width: 150px;float: right;margin-right: -20px;">
                        <button type="button" class="btn btn-sm btn-default btn-flat" @click="setParams(index)">基础参数</button>
                        <button type="button" class="btn btn-sm btn-default btn-flat" @click="setFilter(index)">查询参数</button>
                    </div>
                </div>
            </template>
        </div>
    </div>
    <!--字段设置-->

    <div class="box box-success" v-if="menus[current_db_index]">
        <div class="box-header with-border">
            <h3 class="box-title">
                字段设置
                <button type="button" class="btn btn-info btn-flat" style="margin-left: 20px;width: 140px;">保存</button>
            </h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
        </div>

        <div class="box-body">
            <table class="table table-bordered table-striped dataTable" style="margin-bottom:0" table-layout="fixed">
                <thead>
                    <tr class="">
                        <th class="text-center">字段名</th>
                        <th class="text-center">显示名</th>
                        <th class="text-center" width="150px">展示样式</th>
                        <th class="text-center" width="100px">展示宽度</th>
                        <th class="text-center" width="100px">提示语言</th>
                        <th class="text-center" width="80px">不展示</th>
                        <th class="text-center" width="80px">可排序</th>
                        <th class="text-center" width="80px">可筛选</th>
                        <th class="text-center" width="80px">可显示</th>
                        <th class="text-center" width="50px">图标</th>
                    </tr>
                </thead>
                <tbody class="my_fields">
                <template v-for="(row,index) in menus[current_db_index].fields">
                    <tr :class="index%2 ? 'even' : 'odd'">
                        <td class="text-center">{{row.field}}</td>
                        <td class="text-center"><input class="form-control" type="text" v-model="row.name"></td>
                        <td class="text-center">
                            <select class="form-control" v-model="row.type">
                                <option value="text" :selected="row.type == 'text'">默认文字展示</option>
                                <option value="media" :selected="row.type == 'media'">媒体链接 转 媒体图标</option>
                                <option value="user" :selected="row.type == 'user'">用户ID 转 用户名</option>
                                <option value="timestamp" :selected="row.type == 'timestamp'">时间戳 转 本地时间</option>
                            </select>
                        </td>
                        <td class="text-center"><input class="form-control" type="number" v-model="row.width"></td>
                        <td class="text-center"><input class="form-control" type="text" v-model="row.tooltip"></td>
                        <td class="text-center"><input type="checkbox" v-model="row.show" :checked="row.show"></td>
                        <td class="text-center"><input type="checkbox" v-model="row.sort" :checked="row.sort"></td>
                        <td class="text-center"><input type="checkbox" v-model="row.filter" :checked="row.filter"></td>
                        <td class="text-center"><input type="checkbox" v-model="row.canShow" :checked="row.canShow"></td>
                        <td class="text-center"><i :class="'fa ' + (row.icon ? row.icon : 'fa-fonticons' ) "></i></td>
                    </tr>
                </template>
                </tbody>
            </table>

        </div>
    </div>
</div>



<!-- 基础信息模板 -->
<div id="base" class="table_row" style="display: none">
    <div class="row">
        <div class="col-sm-6">
            <label class="col-sm-3" for="parent_id">父级菜单</label>
            <div class="col-sm-9">
                <select v-model="menu_id" name="parent_id" data-placeholders="选择一个父级菜单，默认：根节点" class="form-control select2-hidden-accessible" style="width: 100%" data-select2-id="parent_id" tabindex="-1" aria-hidden="true">
                    <template v-for="(row, index) in menus">
                        <option :value="row.menu_id" data-select2-id="2" :selected="row.menu_id == menu_id">{{ '　'.repeat(row.level) + row.name}}</option>
                    </template>
                </select>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label for="name" class="col-sm-3 control-label must-start">菜单名称</label>
                <div class="col-sm-9">
                    <div class="input-group">
                        <input name="name" type="text" class="form-control" v-model="menu_name" placeholder="请输入菜单名称">
                        <span class="input-group-addon" onclick="showIcons()"><i class="fa fa-fonticons"></i></span>
                    </div>
                </div>
            </div>
            <input type="hidden" name="icon" value="">
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="col-sm-3">设置表头</label>
                <div class="col-sm-9">
                    <input type="text" v-model="title" class="form-control" placeholder="表头，默认为菜单名称">
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="col-sm-3">设置描述</label>
                <div class="col-sm-9">
                    <input type="text" v-model="subtitle" class="form-control" placeholder="描述，默认为空">
                </div>
            </div>
        </div>
    </div>

    <div class="row" style="display:flex;justify-content: space-between;">
        <label><input type="checkbox" v-model="canSelect" :checked="canSelect">可选择</label>
        <label><input type="checkbox" v-model="canEdit" :checked="canEdit">可编辑</label>
        <label><input type="checkbox" v-model="canFilter" :checked="canFilter">可筛选</label>
        <label><input type="checkbox" v-model="canAppend" :checked="canAppend">可添加</label>
        <label><input type="checkbox" v-model="canDelete" :checked="canDelete">可删除</label>
        <label><input type="checkbox" v-model="canMin" :checked="canMin">可收缩</label>
        <label><input type="checkbox" v-model="canClose" :checked="canClose">可关闭</label>
    </div>
</div>