<div id="user_list" class="box">
    <div class="box-header with-border">
        <h3 class="box-title">数据源列表</h3>
        <a href="/admin/menu/3/item/new" type="button" class="btn btn-success btn-sm" style="margin-left:20px;">添加数据源</a>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table class="table table-bordered table-striped">
            <tbody><tr>
                <th style="width: 50px" class="text-center">#</th>
                <th>名词</th>
                <th>类型</th>
                <th>主机:端口</th>
                <th>用户</th>
                <th>密码</th>
                <th style="width: 150px" class="text-center">操作</th>
            </tr>
            <tr>
                <td class="text-center">1</td>
                <td>商城数据库</td>
                <td>mysql</td>
                <td>127.0.0.1:3306</td>
                <td>root</td>
                <td>1***3</td>
                <td class="text-center">
                    <a id="enable_1" data-val="1" onclick="enabled(1,event);" href="#">禁用</a>
                    <a href="/admin/menu/3/item/1">修改</a>
                    <a onclick="deleted(1)" href="#">删除</a>
                </td>
            </tr>
            <tr>
                <td class="text-center">2</td>
                <td>Blog数据库</td>
                <td>sqlite</td>
                <td>127.0.0.1:3306</td>
                <td>root</td>
                <td>1***3</td>
                <td class="text-center">
                    <a id="enable_1" data-val="1" onclick="enabled(1,event);" href="#">禁用</a>
                    <a href="/admin/menu/3/item/1">修改</a>
                    <a onclick="deleted(1)" href="#">删除</a>
                </td>
            </tr>
            <tr>
                <td class="text-center">3</td>
                <td>大数据数据库</td>
                <td>postgresql</td>
                <td>127.0.0.1:3306</td>
                <td>root</td>
                <td>1***3</td>
                <td class="text-center">
                    <a id="enable_1" data-val="1" onclick="enabled(1,event);" href="#">禁用</a>
                    <a href="/admin/menu/3/item/1">修改</a>
                    <a onclick="deleted(1)" href="#">删除</a>
                </td>
            </tr>
            </tbody></table>
    </div>
    <!-- /.box-body -->
    <div class="box-footer clearfix"><ul class="pagination pagination-sm no-margin pull-right"></ul>
    </div>
</div>


<div id="user_list" class="box">
    <div class="box-header with-border">
        <h3 class="box-title">菜单列表</h3>
        <a href="/admin/menu/3/item/new" type="button" class="btn btn-success btn-sm" style="margin-left:20px;">添加新菜单</a>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table class="table table-bordered table-striped">
            <tbody><tr>
                <th style="width: 50px" class="text-center">#</th>
                <th>菜单名称</th>
                <th>数据源</th>
                <th>表</th>
                <th style="width: 150px" class="text-center">操作</th>
            </tr>
            <tr>
                <td class="text-center">1</td>
                <td>mysql</td>
                <td>127.0.0.1:3306</td>
                <td>root</td>
                <td class="text-center">
                    <a id="enable_1" data-val="1" onclick="enabled(1,event);" href="#">禁用</a>
                    <a href="/admin/menu/3/item/1">修改</a>
                    <a onclick="deleted(1)" href="#">删除</a>
                </td>
            </tr>
            <tr>
                <td class="text-center">2</td>
                <td>sqlite</td>
                <td>127.0.0.1:3306</td>
                <td>root</td>
                <td class="text-center">
                    <a id="enable_1" data-val="1" onclick="enabled(1,event);" href="#">禁用</a>
                    <a href="/admin/menu/3/item/1">修改</a>
                    <a onclick="deleted(1)" href="#">删除</a>
                </td>
            </tr>
            <tr>
                <td class="text-center">3</td>
                <td>postgresql</td>
                <td>127.0.0.1:3306</td>
                <td>root</td>
                <td class="text-center">
                    <a id="enable_1" data-val="1" onclick="enabled(1,event);" href="#">禁用</a>
                    <a href="/admin/menu/3/item/1">修改</a>
                    <a onclick="deleted(1)" href="#">删除</a>
                </td>
            </tr>
            </tbody></table>
    </div>
    <!-- /.box-body -->
    <div class="box-footer clearfix"><ul class="pagination pagination-sm no-margin pull-right"></ul>
    </div>
</div>