<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title"><?=$new?'添加':'修改'?>用户</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form method="post" action="<?=$c->url('update')?>">
        <div class="box-body">
            <div class="form-group">
                <label>登录名</label>
                <input name="name" type="text" class="form-control" placeholder="输入用户名" value="<?=$user->name??''?>">
            </div>
            <div class="form-group">
                <label>显示名</label>
                <input name="nickname" type="text" class="form-control" placeholder="输入昵称" value="<?=$user->nickname??''?>">
            </div>
            <div class="form-group">
                <label>手机号</label>
                <input name="mobile" type="number" class="form-control" placeholder="输入手机号" value="<?=$user->mobile??''?>">
            </div>
            
            <div class="form-group">
                <label>密码</label>
                <input type="password" class="form-control" placeholder="输入密码">
            </div>
            
            <div class="form-group">
                <label>密码确认</label>
                <input name="password" type="password" class="form-control" placeholder="密码确认">
            </div>
            
            <div class="form-group">
                <label>头像</label>
                <input name="image" type="text" class="form-control" placeholder="头像网络地址" value="<?=$user->image??''?>">
            </div>
    
            <div class="form-group">
                <label for="exampleInputFile">选择角色</label>
                <?php
                $role_id = $user->roles->role_id ?? 0;
                foreach($roles as $role){
                    $check = $role->role_id == $role_id ? ' checked=""' : '';
                    if(!$c->isAllowed('update', $role->role_id, $role_id)) continue;
                ?>
                <div class="radio"><label><input<?=$check?> type="radio" name="role_id" value="<?=$role->role_id?>"><?=$role->name?></label></div>
                <?php } ?>
            </div>
        </div>
        <!-- /.box-body -->
        
        <div class="box-footer">
            <button type="submit" class="btn btn-primary">提交</button>
        </div>
    </form>
</div>