<div id="user_list" class="box">
    <div class="box-header with-border">
        <h3 class="box-title">用户列表</h3>
        <?php if($c->isAllowed('new', 0, $c->getUserId())) { ?>
        <a href="<?=$c->url('new')?>" type="button" class="btn btn-success btn-sm" style="margin-left:20px;">添加新用户</a>
        <?php } ?>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table class="table table-bordered table-striped">
            <tr>
                <th style="width: 50px" class="text-center">#</th>
                <th>登录名</th>
                <th>用户名</th>
                <th>角色</th>
                <th>手机号码</th>
                <th style="width: 50px" class="text-center">可用</th>
                <th style="width: 150px" class="text-center">操作</th>
            </tr>
            <?php foreach($users as $user){ if(!$c->isAllowed('index', $user->user_id, $c->getUserId())) continue; ?>
            <tr>
            <td class="text-center"><?=$user->user_id?></td>
                <td><?=$user->name?></td>
                <td><?=$user->nickname?></td>
                <td><?=$user->Role ? $user->Role->name : '未指定'?></td>
                <td><?=$user->mobile?></td>
                <td id="status_<?=$user->user_id?>" class="text-center"><?=$user->is_enabled?'是':'否'?></td>
                <td class="text-center">
                    <?php if($c->isAllowed('update', $user->user_id, $c->getUserId())) { ?>
                    <a id="enable_<?=$user->user_id?>" data-val="<?=$user->is_enabled?>" onclick="enabled(<?=$user->user_id?>,event);" href="#"><?=$user->is_enabled?'禁用':'启用'?></a>
                    <a href="<?=$c->url('display',['item_id'=>$user->user_id])?>">修改</a>
                    <?php } ?>
                    <?php if($c->isAllowed('delete', $user->user_id, $c->getUserId())) { ?>
                    <a onclick="deleted(<?=$user->user_id?>)" href="#">删除</a>
                    <?php } ?>
                </td>
            </tr>
            <?php } ?>
        </table>
    </div>
    <!-- /.box-body -->
    <?=$page?>
</div>

<script>
var url = '<?=$enable_url?>';
url = url.substr(0,url.length-2)
function enabled(user_id,e){
    var obj = $(e.target);
    var val = obj.data('val') ? 0 : 1;
    $.ajax(url + '/'+ user_id + '/type/enable/enabled/' + val).done(function(d){
        if(d.ok){
            $('#status_'+user_id).text( val ? '是'   : '否'   );
            obj.text( val ? '禁用' : '启用' );
            obj.data('val', val);
        }
    });
}

function deleted(user_id){
    showDialogs({
        title:'确认删除用户吗？',
        body:'如果你只是想要用户短时间不能登录，可以选择【禁用】用户',
        ok:{
            text:'确认', click:function(){
                $.ajax(url + '/'+ user_id, {method:'DELETE'}).done(function(d){
                    location.reload();
                });
            }
        },
        close:{
            text:'取消' ,click:function(o){o.close();}
        }
    });
}
</script>
