<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title><?=$title?></title>
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

<?php if($css) foreach($css['before'] as $_) echo $_; ?>
<?php if($style) foreach($style['before'] as $_) echo $_; ?>

<link rel="stylesheet" href="/dist/bower_components/bootstrap/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="/dist/bower_components/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" href="/dist/bower_components/Ionicons/css/ionicons.min.css">
<link rel="stylesheet" href="/dist/bower_components/morris.js/morris.css">
<link rel="stylesheet" href="/dist/adminlte/css/AdminLTE.min.css">
<link rel="stylesheet" href="/dist/adminlte/css/skins/_all-skins.min.css">
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
<link rel="stylesheet" href="/dist/css/animate.css">
<script src="/dist/bower_components/jquery/dist/jquery.min.js"></script>

<?php if($css) foreach($css['after'] as $_) echo $_; ?>
<?php if($style) foreach($style['after'] as $_) echo $_; ?>