<?php if($js) foreach($js['before'] as $_) echo $_; ?>
<?php if($script) foreach($script['before'] as $_) echo $_; ?>

<!-- jQuery UI 1.11.4 -->
<script src="/dist/bower_components/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>


<!-- Bootstrap 3.3.7 -->
<script src="/dist/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Morris.js charts -->
<script src="/dist/bower_components/raphael/raphael.min.js"></script>
<script src="/dist/bower_components/morris.js/morris.min.js"></script>
<!-- Sparkline -->
<script src="/dist/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
<!-- jvectormap -->
<script src="/dist/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="/dist/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- jQuery Knob Chart -->
<script src="/dist/bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="/dist/bower_components/moment/min/moment.min.js"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="/dist/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<!-- Slimscroll -->
<script src="/dist/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="/dist/bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="/dist/adminlte/js/adminlte.js"></script>

<!--<script src="/dist/AmazeUI-2.7.2/assets/js/amazeui.min.js" type="text/javascript"></script>-->
<!--<script src="/dist/AmazeUI-2.7.2/switch/amazeui.switch.min.js" type="text/javascript"></script>-->
<script src="/dist/public/common.js"></script>
<script src="/dist/admin.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<!--<script src="/dist/adminlte/js/pages/dashboard.js"></script>-->
<!-- AdminLTE for demo purposes -->
<!--<script src="/dist/adminlte/js/demo.js"></script>-->

<?php if($js) foreach($js['after'] as $_) echo $_; ?>
<?php if($script) foreach($script['after'] as $_) echo $_; ?>
