<?php if($js) foreach($js['before'] as $_) echo $_; ?>
<?php if($script) foreach($script['before'] as $_) echo $_; ?>

<script src="/dist/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="/dist/bower_components/morris.js/morris.min.js"></script>
<script src="/dist/bower_components/fastclick/lib/fastclick.js"></script>
<script src="/dist/adminlte/js/adminlte.js"></script>
<script src="/dist/js/common.js"></script>

<?php if($js) foreach($js['after'] as $_) echo $_; ?>
<?php if($script) foreach($script['after'] as $_) echo $_; ?>