<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title><?=$title?></title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

<?php if($css) foreach($css['before'] as $_) echo $_; ?>
<?php if($style) foreach($style['before'] as $_) echo $_; ?>

<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="/dist/bower_components/bootstrap/dist/css/bootstrap.min.css">
<!-- Font Awesome -->
<link rel="stylesheet" href="/dist/bower_components/font-awesome/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="/dist/bower_components/Ionicons/css/ionicons.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="/dist/adminlte/css/AdminLTE.min.css">
<!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="/dist/adminlte/css/skins/_all-skins.min.css">
<!-- Morris chart -->
<link rel="stylesheet" href="/dist/bower_components/morris.js/morris.css">
<!-- jvectormap -->
<link rel="stylesheet" href="/dist/bower_components/jvectormap/jquery-jvectormap.css">
<!-- Date Picker -->
<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="/dist/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
<!--public animate.css -->
<link rel="stylesheet" href="/dist/public/css/animate.css">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<!-- jQuery 3 -->
<script src="/dist/bower_components/jquery/dist/jquery.min.js"></script>

<!--<link href="/dist/AmazeUI-2.7.2/assets/css/amazeui.min.css" rel="stylesheet" type="text/css"/>-->
<!--<link href="/dist/AmazeUI-2.7.2/switch/amazeui.switch.css" rel="stylesheet" type="text/css"/>-->
<!-- Google Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

<?php if($css) foreach($css['after'] as $_) echo $_; ?>
<?php if($style) foreach($style['after'] as $_) echo $_; ?>
