<?php
namespace plugins\Tables\Models;
use PowerModelBase as PMB;

class TablesFields extends PMB{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->setSource(\PA::$config->path('pa_db.prefix').'tables_fields');
    }
}
